name: Central Package Management - Regular Checks
on:
  pull_request:
    paths:
      - 'central-package-management/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./central-package-management
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Build Solution
        run: dotnet build -c Release
