name: Projects - Regular Checks

on:
  pull_request:
    branches:
      - main
      - 'epic/**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Build Solution
        run: dotnet build
      - name: Run Tests
        run: dotnet test
