name: Projects - Regular Checks

on:
  pull_request:
    branches:
      - main
      - 'epic/**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Restore Dependencies
        run: dotnet restore
      - name: Format Solution
        run: dotnet format --no-restore --verify-no-changes --verbosity diagnostic
      - name: Build Solution
        run: dotnet build --no-restore -c Release
      - name: Run Tests
        run: dotnet test
