name: Publish Container

on:
  pull_request:
    branches:
      - main
      - 'epic/**'

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Publish
        working-directory: ./publish-over-dockerfile/PublishOverDockerfile
        run: dotnet publish --os linux --arch x64 /t:PublishContainer -c Release
