name: Source Generator - Regular Checks
on:
  pull_request:
    paths:
      - 'source-generator/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source-generator
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
      - name: Build Solution
        run: |
          dotnet build -c Release
