name: UnitTesting - Regular Checks
on:
  pull_request:
    paths:
      - 'unit-testing/**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
      - name: Move project dir
        run: cd unit-testing
      - name: Build Solution
        run: dotnet build -c Release
      - name: Run Tests
        run: dotnet test
