name: UnitTesting - Regular Checks
on:
  pull_request:
    paths:
      - 'unit-testing/**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./unit-testing/test
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Build Solution
        run: dotnet build
      - name: Run Tests
        run: dotnet test
